name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/devops_project_2

          # Pull latest code
          git pull origin main

          # Activate virtual environment
          source /home/ubuntu/venv/bin/activate

          # Stop old Flask process if running
          pkill -f app.py || true

          # Start Flask in background and log output
          nohup python3 app.py > flask.log 2>&1 &
        EOF
